<!--
This HTML is auto-generated.  DO NOT EDIT THIS FILE!  If you are writing a new
PEP, see http://www.python.org/dev/peps/pep-0001 for instructions and links
to templates.  DO NOT USE THIS HTML FILE AS YOUR TEMPLATE!
-->
<table class="rfc2822 docutils field-list" frame="void" rules="none">
<col class="field-name" />
<col class="field-body" />
<tbody valign="top">
<tr class="field"><th class="field-name">PEP:</th><td class="field-body">522</td>
</tr>
<tr class="field"><th class="field-name">Title:</th><td class="field-body">Allow BlockingIOError in security sensitive APIs on Linux</td>
</tr>
<tr class="field"><th class="field-name">Version:</th><td class="field-body">$Revision$</td>
</tr>
<tr class="field"><th class="field-name">Last-Modified:</th><td class="field-body"><a class="reference external" href="https://hg.python.org/peps/file/tip/pep-0522.txt">$Date$</a></td>
</tr>
<tr class="field"><th class="field-name">Author:</th><td class="field-body">Nick Coghlan &lt;ncoghlan&#32;&#97;t&#32;gmail.com&gt;, Nathaniel J. Smith &lt;njs&#32;&#97;t&#32;pobox.com&gt;</td>
</tr>
<tr class="field"><th class="field-name">Status:</th><td class="field-body">Draft</td>
</tr>
<tr class="field"><th class="field-name">Type:</th><td class="field-body">Standards Track</td>
</tr>
<tr class="field"><th class="field-name">Content-Type:</th><td class="field-body"><a class="reference external" href="/dev/peps/pep-0012">text/x-rst</a></td>
</tr>
<tr class="field"><th class="field-name">Created:</th><td class="field-body">16 June 2016</td>
</tr>
<tr class="field"><th class="field-name">Python-Version:</th><td class="field-body">3.6</td>
</tr>
</tbody>
</table>
<hr />
<div class="contents topic" id="contents">
<p class="topic-title first">Contents</p>
<ul class="simple">
<li><a class="reference internal" href="#abstract" id="id17">Abstract</a></li>
<li><a class="reference internal" href="#proposal" id="id18">Proposal</a><ul>
<li><a class="reference internal" href="#changing-os-urandom-on-linux" id="id19">Changing <tt class="docutils literal">os.urandom()</tt> on Linux</a></li>
<li><a class="reference internal" href="#related-changes" id="id20">Related changes</a></li>
<li><a class="reference internal" href="#limitations-on-scope" id="id21">Limitations on scope</a></li>
</ul>
</li>
<li><a class="reference internal" href="#rationale" id="id22">Rationale</a><ul>
<li><a class="reference internal" href="#raising-blockingioerror-in-os-urandom-on-linux" id="id23">Raising <tt class="docutils literal">BlockingIOError</tt> in <tt class="docutils literal">os.urandom()</tt> on Linux</a></li>
<li><a class="reference internal" href="#issuing-a-warning-for-potentially-predictable-internal-hash-initialization" id="id24">Issuing a warning for potentially predictable internal hash initialization</a></li>
<li><a class="reference internal" href="#allowing-potentially-predictable-random-module-initialization" id="id25">Allowing potentially predictable <tt class="docutils literal">random</tt> module initialization</a></li>
</ul>
</li>
<li><a class="reference internal" href="#backwards-compatibility-impact-assessment" id="id26">Backwards Compatibility Impact Assessment</a><ul>
<li><a class="reference internal" href="#unaffected-applications" id="id27">Unaffected Applications</a></li>
<li><a class="reference internal" href="#affected-security-sensitive-applications" id="id28">Affected security sensitive applications</a></li>
<li><a class="reference internal" href="#affected-non-security-sensitive-applications" id="id29">Affected non-security sensitive applications</a></li>
<li><a class="reference internal" href="#affected-linux-specific-non-security-sensitive-applications" id="id30">Affected Linux specific non-security sensitive applications</a></li>
</ul>
</li>
<li><a class="reference internal" href="#additional-background" id="id31">Additional Background</a><ul>
<li><a class="reference internal" href="#why-propose-this-now" id="id32">Why propose this now?</a></li>
<li><a class="reference internal" href="#the-cross-platform-behaviour-of-os-urandom" id="id33">The cross-platform behaviour of <tt class="docutils literal">os.urandom()</tt></a></li>
<li><a class="reference internal" href="#problems-with-the-behaviour-of-dev-urandom-on-linux" id="id34">Problems with the behaviour of <tt class="docutils literal">/dev/urandom</tt> on Linux</a></li>
<li><a class="reference internal" href="#consequences-of-getrandom-availability-for-python" id="id35">Consequences of <tt class="docutils literal">getrandom()</tt> availability for Python</a></li>
</ul>
</li>
<li><a class="reference internal" href="#references" id="id36">References</a></li>
<li><a class="reference internal" href="#copyright" id="id37">Copyright</a></li>
</ul>
</div>
<div class="section" id="abstract">
<h1><a class="toc-backref" href="#id17">Abstract</a></h1>
<p>A number of APIs in the standard library that return random values nominally
suitable for use in security sensitive operations currently have an obscure
Linux-specific failure mode that allows them to return values that are not,
in fact, suitable for such operations.</p>
<p>This PEP proposes changing such failures in Python 3.6 from the current silent,
hard to detect, and hard to debug, errors to easily detected and debugged errors
by raising <tt class="docutils literal">BlockingIOError</tt> with a suitable error message, allowing
developers the opportunity to unambiguously specify their preferred approach
for handling the situation.</p>
<p>The APIs affected by this change would be:</p>
<ul class="simple">
<li><tt class="docutils literal">os.urandom</tt></li>
<li><tt class="docutils literal">random.SystemRandom</tt></li>
<li>the new <tt class="docutils literal">secrets</tt> module added by <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a></li>
</ul>
<p>The new exception would potentially be encountered in the following situations:</p>
<ul class="simple">
<li>Python code calling these APIs during Linux system initialization</li>
<li>Python code running on improperly initialized Linux systems (e.g. embedded
hardware without adequate sources of entropy to seed the system random number
generator, or Linux VMs that aren't configured to accept entropy from the
VM host)</li>
</ul>
<p>CPython interpreter initialization and <tt class="docutils literal">random</tt> module initialization would
also be updated to gracefully fall back to alternative seeding options if the
system random number generator is not ready.</p>
</div>
<div class="section" id="proposal">
<h1><a class="toc-backref" href="#id18">Proposal</a></h1>
<div class="section" id="changing-os-urandom-on-linux">
<h2><a class="toc-backref" href="#id19">Changing <tt class="docutils literal">os.urandom()</tt> on Linux</a></h2>
<p>This PEP proposes that in Python 3.6+, <tt class="docutils literal">os.urandom()</tt> be updated to call
the new Linux <tt class="docutils literal">getrandom()</tt> syscall in non-blocking mode if available and
raise <tt class="docutils literal">BlockingIOError: system random number generator is not ready</tt> if
the kernel reports that the call would block.</p>
<p>This behaviour will then
propagate through to higher level standard library APIs that depend on
<tt class="docutils literal">os.urandom</tt> (specifically <tt class="docutils literal">random.SystemRandom</tt> and the new <tt class="docutils literal">secrets</tt>
module introduced by <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a>).</p>
<p>In all cases, as soon as a call to one of these security sensitive APIs
succeeds, all future calls to these APIs in that process will succeed (once
the operating system random number generator is ready after system boot, it
remains ready).</p>
</div>
<div class="section" id="related-changes">
<h2><a class="toc-backref" href="#id20">Related changes</a></h2>
<p>Currently, SipHash initialization and <tt class="docutils literal">random</tt> module initialization
both gather random bytes using the same code that underlies
<tt class="docutils literal">os.urandom</tt>. This PEP proposes to modify these so that in situations where
<tt class="docutils literal">os.urandom</tt> would raise a <tt class="docutils literal">BlockingIOError</tt>, they automatically
fall back on potentially more predictable sources of randomness (and in the
SipHash case, print a warning message to <tt class="docutils literal">stderr</tt> indicating that that
particular Python process should not be used to process untrusted data).</p>
<p>To transparently accommodate a potential future where Linux adopts the same
&quot;potentially blocking during system initialization&quot; <tt class="docutils literal">/dev/urandom</tt> behaviour
used by other *nix systems, this fallback source of randomness will <em>not</em> be
the <tt class="docutils literal">/dev/urandom</tt> device.</p>
</div>
<div class="section" id="limitations-on-scope">
<h2><a class="toc-backref" href="#id21">Limitations on scope</a></h2>
<p>No changes are proposed for Windows or Mac OS X systems, as neither of those
platforms provides any mechanism to run Python code before the operating
system random number generator has been initialized. Mac OS X goes so far as
to kernel panic and abort the boot process if it can't properly initialize the
random number generator (although Apple's restrictions on the supported
hardware platforms make that exceedingly unlikely in practice).</p>
<p>Similarly, no changes are proposed for other *nix systems where
<tt class="docutils literal">os.urandom()</tt> will currently block waiting for the system random number
generator to be initialized, rather than returning values that are potentially
unsuitable for use in security sensitive applications.</p>
<p>While other *nix systems that offer a non-blocking API for requesting random
numbers suitable for use in security sensitive applications could potentially
receive a similar update to the one proposed for Linux in this PEP, such
changes are out of scope for this particular proposal.</p>
<p>Python's behaviour on older Linux systems that do not offer the new
<tt class="docutils literal">getrandom()</tt> syscall will also remain unchanged.</p>
</div>
</div>
<div class="section" id="rationale">
<h1><a class="toc-backref" href="#id22">Rationale</a></h1>
<div class="section" id="raising-blockingioerror-in-os-urandom-on-linux">
<h2><a class="toc-backref" href="#id23">Raising <tt class="docutils literal">BlockingIOError</tt> in <tt class="docutils literal">os.urandom()</tt> on Linux</a></h2>
<p>For several years now, the security community's guidance has been to use
<tt class="docutils literal">os.urandom()</tt> (or the <tt class="docutils literal">random.SystemRandom()</tt> wrapper) when implementing
security sensitive operations in Python.</p>
<p>To help improve API discoverability and make it clearer that secrecy and
simulation are not the same problem (even though they both involve
random numbers), <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a> collected several of the one line recipes based
on the lower level <tt class="docutils literal">os.urandom()</tt> API into a new <tt class="docutils literal">secrets</tt> module.</p>
<p>However, this guidance has also come with a longstanding caveat: developers
writing security sensitive software at least for Linux, and potentially for
some other *BSD systems, may need to wait until the operating system's
random number generator is ready before relying on it for security sensitive
operations. This generally only occurs if <tt class="docutils literal">os.urandom()</tt> is read very
early in the system initialization process, or on systems with few sources of
available entropy (e.g. some kinds of virtualized or embedded systems), but
unfortunately the exact conditions that trigger this are difficult to predict,
and when it occurs then there is no direct way for userspace to tell it has
happened without querying operating system specific interfaces.</p>
<p>On *BSD systems (if the particular *BSD variant allows the problem to occur
at all), encountering this situation means <tt class="docutils literal">os.urandom()</tt> will either block
waiting for the system random number generator to be ready (the associated
symptom would be for the affected script to pause unexpectedly on the first
call to <tt class="docutils literal">os.urandom()</tt>) or else will behave the same way as it does on Linux.</p>
<p>On Linux, in Python versions up to and including Python 3.4, and in
Python 3.5 maintenance versions following Python 3.5.2, there's no clear
indicator to developers that their software may not be working as expected
when run early in the Linux boot process, or on hardware without good
sources of entropy to seed the operating system's random number generator: due
to the behaviour of the underlying <tt class="docutils literal">/dev/urandom</tt> device, <tt class="docutils literal">os.urandom()</tt>
on Linux returns a result either way, and it takes extensive statistical
analysis to show that a security vulnerability exists.</p>
<p>By contrast, if <tt class="docutils literal">BlockingIOError</tt> is raised in those situations, then
developers using Python 3.6+ can easily choose their desired behaviour:</p>
<ol class="arabic simple">
<li>Loop until the call succeeds (security sensitive)</li>
<li>Switch to using the random module (non-security sensitive)</li>
<li>Switch to reading <tt class="docutils literal">/dev/urandom</tt> directly (non-security sensitive)</li>
</ol>
</div>
<div class="section" id="issuing-a-warning-for-potentially-predictable-internal-hash-initialization">
<h2><a class="toc-backref" href="#id24">Issuing a warning for potentially predictable internal hash initialization</a></h2>
<p>The challenge for internal hash initialization is that it might be very
important to initialize SipHash with a reliably unpredictable random seed
(for processes that are exposed to potentially hostile input) or it might be
totally unimportant (for processes that never have to deal with untrusted data).</p>
<p>The Python runtime has no way to know which case a given invocation involves,
which means that if we allow SipHash initialization to block or error out,
then our intended security enhancement may break code that is already safe
and working fine, which is unacceptable -- especially since we are reasonably
confident that most Python invocations that might run during Linux system
initialization fall into this category (exposure to untrusted input tends to
involve network access, which typically isn't brought up until after the system
random number generator is initialized).</p>
<p>However, at the same time, since Python has no way to know whether any given
invocation needs to handle untrusted data, when the default SipHash
initialization fails this <em>might</em> indicate a genuine security problem, which
should not be allowed to pass silently.</p>
<p>Accordingly, if internal hash initialization needs to fall back to a potentially
predictable seed due to the system random number generator not being ready, it
will also emit a warning message on <tt class="docutils literal">stderr</tt> to say that the system random
number generator is not available and that processing potentially hostile
untrusted data should be avoided.</p>
</div>
<div class="section" id="allowing-potentially-predictable-random-module-initialization">
<h2><a class="toc-backref" href="#id25">Allowing potentially predictable <tt class="docutils literal">random</tt> module initialization</a></h2>
<p>Other than for <tt class="docutils literal">random.SystemRandom</tt> (which is a relatively thin
wrapper around <tt class="docutils literal">os.urandom</tt>), the <tt class="docutils literal">random</tt> module has never made
any guarantees that the numbers it generates are suitable for use in
security sensitive operations, so the use of the system random number
generator to seed the default Mersenne Twister instance is mainly beneficial
as a harm mitigation measure for code that is using the <tt class="docutils literal">random</tt> module
inappropriately.</p>
<p>Since a single call to <tt class="docutils literal">os.urandom()</tt> is cheap once the system random
number generator has been initialized it makes sense to retain that as the
default behaviour, but there's no need to issue a warning when falling back to
a potentially more predictable alternative when necessary (in such cases,
a warning will typically already have been issued as part of interpreter
startup, as the only way for the call when importing the random module to
fail without the implicit call during interpreter startup also failing if for
the latter to have been skipped by entirely disabling the hash randomization
mechanism).</p>
</div>
</div>
<div class="section" id="backwards-compatibility-impact-assessment">
<h1><a class="toc-backref" href="#id26">Backwards Compatibility Impact Assessment</a></h1>
<p>Similar to <a class="reference external" href="/dev/peps/pep-0476">PEP 476</a>, this is a proposal to turn a previously silent security
failure into a noisy exception that requires the application developer to
make an explicit decision regarding the behaviour they desire.</p>
<p>As no changes are proposed for operating systems other than Linux,
<tt class="docutils literal">os.urandom()</tt> retains its existing behaviour as a nominally blocking API
that is non-blocking in practice due to the difficulty of scheduling Python
code to run before the operating system random number generator is ready. We
believe it may be possible to encounter problems akin to those described in
this PEP on at least some *BSD variants, but nobody has explicitly
demonstrated that. On Mac OS X and Windows, it appears to be straight up
impossible to even try to run a Python interpreter that early in the boot
process.</p>
<p>On Linux, <tt class="docutils literal">os.urandom()</tt> retains its status as a guaranteed non-blocking API.
However, the means of achieving that status changes in the specific case of
the operating system random number generator not being ready for use in security
sensitive operations: historically it would return potentially predictable
random data, with this PEP it would change to raise <tt class="docutils literal">BlockingIOError</tt>.</p>
<p>Developers of affected applications would then be required to make one of the
following changes to gain forward compatibility with Python 3.6, based on the
kind of application they're developing.</p>
<div class="section" id="unaffected-applications">
<h2><a class="toc-backref" href="#id27">Unaffected Applications</a></h2>
<p>The following kinds of applications would be entirely unaffected by the change,
regardless of whether or not they perform security sensitive operations:</p>
<ul class="simple">
<li>applications that don't support Linux</li>
<li>applications that are only run on desktops or conventional servers</li>
<li>applications that are only run after the system RNG is ready</li>
</ul>
<p>Applications in this category simply won't encounter the new exception, so it
will be reasonable for developers to wait and see if they receive
Python 3.6 compatibility bugs related to the new runtime behaviour, rather than
attempting to pre-emptively determine whether or not they're affected.</p>
</div>
<div class="section" id="affected-security-sensitive-applications">
<h2><a class="toc-backref" href="#id28">Affected security sensitive applications</a></h2>
<p>Security sensitive applications would need to either change their system
configuration so the application is only started after the operating system
random number generator is ready for security sensitive operations, or else
change their code to busy loop until the operating system is ready:</p>
<pre class="literal-block">
def blocking_urandom(num_bytes):
    while True:
        try:
            return os.urandom(num_bytes)
        except BlockingIOError:
            pass
</pre>
</div>
<div class="section" id="affected-non-security-sensitive-applications">
<h2><a class="toc-backref" href="#id29">Affected non-security sensitive applications</a></h2>
<p>Non-security sensitive applications that don't want to assume access to
<tt class="docutils literal">/dev/urandom</tt> (or assume a non-blocking implementation of that device)
can be updated to use the <tt class="docutils literal">random</tt> module as a fallback option:</p>
<pre class="literal-block">
def pseudorandom_fallback(num_bytes):
    try:
        return os.urandom(num_bytes)
    except BlockingIOError:
        return random.getrandbits(num_bytes*8).to_bytes(num_bytes, &quot;little&quot;)
</pre>
<p>Depending on the application, it may also be appropriate to skip accessing
<tt class="docutils literal">os.urandom</tt> at all, and instead rely solely on the <tt class="docutils literal">random</tt> module.</p>
</div>
<div class="section" id="affected-linux-specific-non-security-sensitive-applications">
<h2><a class="toc-backref" href="#id30">Affected Linux specific non-security sensitive applications</a></h2>
<p>Non-security sensitive applications that don't need to worry about cross
platform compatibility and are willing to assume that <tt class="docutils literal">/dev/urandom</tt> on
Linux will always retain its current behaviour can be updated to access
<tt class="docutils literal">/dev/urandom</tt> directly:</p>
<pre class="literal-block">
def dev_urandom(num_bytes):
    with open(&quot;/dev/urandom&quot;, &quot;rb&quot;) as f:
        return f.read(num_bytes)
</pre>
<p>However, pursuing this option has the downside of contributing to ensuring
that the default behaviour of Linux at the operating system level can never
be changed.</p>
</div>
</div>
<div class="section" id="additional-background">
<h1><a class="toc-backref" href="#id31">Additional Background</a></h1>
<div class="section" id="why-propose-this-now">
<h2><a class="toc-backref" href="#id32">Why propose this now?</a></h2>
<p>The main reason is because the Python 3.5.0 release switched to using the new
Linux <tt class="docutils literal">getrandom()</tt> syscall when available in order to avoid consuming a
file descriptor <a class="footnote-reference" href="#id9" id="id1">[1]</a>, and this had the side effect of making the following
operations block waiting for the system random number generator to be ready:</p>
<ul class="simple">
<li><tt class="docutils literal">os.urandom</tt> (and APIs that depend on it)</li>
<li>importing the <tt class="docutils literal">random</tt> module</li>
<li>initializing the randomized hash algorithm used by some builtin types</li>
</ul>
<p>While the first of those behaviours is arguably desirable (and consistent with
<tt class="docutils literal">os.urandom</tt>'s existing behaviour on other operating systems), the latter two
behaviours are unnecessary and undesirable, and the last one is now known to
cause a system level deadlock when attempting to run Python scripts during the
Linux init process with Python 3.5.0 or 3.5.1 <a class="footnote-reference" href="#id10" id="id2">[2]</a>, while the second one can
cause problems when using virtual machines without robust entropy sources
configured <a class="footnote-reference" href="#id11" id="id3">[3]</a>.</p>
<p>Since decoupling these behaviours in CPython will involve a number of
implementation changes more appropriate for a feature release than a maintenance
release, the relatively simple resolution applied in Python 3.5.2 was to revert
all three of them to a behaviour similar to that of previous Python versions:
if the new Linux syscall indicates it will block, then Python 3.5.2 will
implicitly fall back on reading <tt class="docutils literal">/dev/urandom</tt> directly <a class="footnote-reference" href="#id12" id="id4">[4]</a>.</p>
<p>However, this bug report <em>also</em> resulted in a range of proposals to add <em>new</em>
APIs like <tt class="docutils literal">os.getrandom()</tt> <a class="footnote-reference" href="#id13" id="id5">[5]</a>, <tt class="docutils literal">os.urandom_block()</tt> <a class="footnote-reference" href="#id14" id="id6">[6]</a>,
<tt class="docutils literal">os.pseudorandom()</tt> and <tt class="docutils literal">os.cryptorandom()</tt> <a class="footnote-reference" href="#id15" id="id7">[7]</a>, or adding new optional
parameters to <tt class="docutils literal">os.urandom()</tt> itself <a class="footnote-reference" href="#id16" id="id8">[8]</a>, and then attempting to educate
users on when they should call those APIs instead of just using a plain
<tt class="docutils literal">os.urandom()</tt> call.</p>
<p>These proposals represent dramatic overreactions, as the question of reliably
obtaining random numbers suitable for security sensitive work on Linux is a
relatively obscure problem of interest mainly to operating system developers
and embedded systems programmers, that in no way justifies cluttering up the
Python standard library's cross-platform APIs with new Linux-specific concerns.
This is especially so with the <tt class="docutils literal">secrets</tt> module already being added as the
&quot;use this and don't worry about the low level details&quot; option for developers
writing security sensitive software that for some reason can't rely on even
higher level domain specific APIs (like web frameworks) and also don't need to
worry about Python versions prior to Python 3.6.</p>
<p>That said, it's also the case that low cost ARM devices are becoming
increasingly prevalent, with a lot of them running Linux, and a lot of folks
writing Python applications that run on those devices. That creates an
opportunity to take an obscure security problem that currently requires a lot
of knowledge about Linux boot processes and provably unpredictable random
number generation to diagnose and resolve, and instead turn it into a
relatively mundane and easy-to-find-in-an-internet-search runtime exception.</p>
</div>
<div class="section" id="the-cross-platform-behaviour-of-os-urandom">
<h2><a class="toc-backref" href="#id33">The cross-platform behaviour of <tt class="docutils literal">os.urandom()</tt></a></h2>
<p>On operating systems other than Linux, <tt class="docutils literal">os.urandom()</tt> may already block
waiting for the operating system's random number generator to be ready. This
will happen at most once in the lifetime of the process, and the call is
subsequently guaranteed to be non-blocking.</p>
<p>Linux is unique in that, even when the operating system's random number
generator doesn't consider itself ready for use in security sensitive
operations, reading from the <tt class="docutils literal">/dev/urandom</tt> device will return random values
based on the entropy it has available.</p>
<p>This behaviour is potentially problematic, so Linux 3.17 added a new
<tt class="docutils literal">getrandom()</tt> syscall that (amongst other benefits) allows callers to
either block waiting for the random number generator to be ready, or
else request an error return if the random number generator is not ready.
Notably, the new API does <em>not</em> support the old behaviour of returning
data that is not suitable for security sensitive use cases.</p>
<p>Versions of Python prior up to and including Python 3.4 access the
Linux <tt class="docutils literal">/dev/urandom</tt> device directly.</p>
<p>Python 3.5.0 and 3.5.1 called <tt class="docutils literal">getrandom()</tt> in blocking mode in order to
avoid the use of a file descriptor to access <tt class="docutils literal">/dev/urandom</tt>. While there
were no specific problems reported due to <tt class="docutils literal">os.urandom()</tt> blocking in user
code, there <em>were</em> problems due to CPython implicitly invoking the blocking
behaviour during interpreter startup and when importing the <tt class="docutils literal">random</tt> module.</p>
<p>Rather than trying to decouple SipHash initialization from the
<tt class="docutils literal">os.urandom()</tt> implementation, Python 3.5.2 switched to calling
<tt class="docutils literal">getrandom()</tt> in non-blocking mode, and falling back to reading from
<tt class="docutils literal">/dev/urandom</tt> if the syscall indicates it will block.</p>
<p>As a result of the above, <tt class="docutils literal">os.urandom()</tt> in all Python versions up to and
including Python 3.5 propagate the behaviour of the underling <tt class="docutils literal">/dev/urandom</tt>
device to Python code.</p>
</div>
<div class="section" id="problems-with-the-behaviour-of-dev-urandom-on-linux">
<h2><a class="toc-backref" href="#id34">Problems with the behaviour of <tt class="docutils literal">/dev/urandom</tt> on Linux</a></h2>
<p>The Python <tt class="docutils literal">os</tt> module has largely co-evolved with Linux APIs, so having
<tt class="docutils literal">os</tt> module functions closely follow the behaviour of their Linux operating
system level counterparts when running on Linux is typically considered to be
a desirable feature.</p>
<p>However, <tt class="docutils literal">/dev/urandom</tt> represents a case where the current behaviour is
acknowledged to be problematic, but fixing it unilaterally at the kernel level
has been shown to prevent some Linux distributions from booting (at least in
part due to components like Python currently using it for
non-security-sensitive purposes early in the system initialization process).</p>
<p>As an analogy, consider the following two functions:</p>
<pre class="literal-block">
def generate_example_password():
    &quot;&quot;&quot;Generates passwords solely for use in code examples&quot;&quot;&quot;
    return generate_unpredictable_password()

def generate_actual_password():
    &quot;&quot;&quot;Generates actual passwords for use in real applications&quot;&quot;&quot;
    return generate_unpredictable_password()
</pre>
<p>If you think of an operating system's random number generator as a method for
generating unpredictable, secret passwords, then you can think of Linux's
<tt class="docutils literal">/dev/urandom</tt> as being implemented like:</p>
<pre class="literal-block">
# Oversimplified artist's conception of the kernel code
# implementing /dev/urandom
def generate_unpredictable_password():
    if system_rng_is_ready:
        return use_system_rng_to_generate_password()
    else:
        # we can't make an unpredictable password; silently return a
        # potentially predictable one instead:
        return &quot;p4ssw0rd&quot;
</pre>
<p>In this scenario, the author of <tt class="docutils literal">generate_example_password</tt> is fine - even if
<tt class="docutils literal">&quot;p4ssw0rd&quot;</tt> shows up a bit more often than they expect, it's only used in
examples anyway. However, the author of <tt class="docutils literal">generate_actual_password</tt> has a
problem - how do they prove that their calls to
<tt class="docutils literal">generate_unpredictable_password</tt> never follow the path that returns a
predictable answer?</p>
<p>In real life it's slightly more complicated than this, because there
might be some level of system entropy available -- so the fallback might
be more like <tt class="docutils literal">return <span class="pre">random.choice([&quot;p4ssword&quot;,</span> &quot;passw0rd&quot;,
<span class="pre">&quot;p4ssw0rd&quot;])</span></tt> or something even more variable and hence only statistically
predictable with better odds than the author of <tt class="docutils literal">generate_actual_password</tt>
was expecting. This doesn't really make things more provably secure, though;
mostly it just means that if you try to catch the problem in the obvious way --
<tt class="docutils literal">if returned_password == &quot;p4ssw0rd&quot;: raise UhOh</tt> -- then it doesn't work,
because <tt class="docutils literal">returned_password</tt> might instead be <tt class="docutils literal">p4ssword</tt> or even
<tt class="docutils literal">pa55word</tt>, or just an arbitrary 64 bit sequence selected from fewer than
2**64 possibilities. So this rough sketch does give the right general idea of
the consequences of the &quot;more predictable than expected&quot; fallback behaviour,
even though it's thoroughly unfair to the Linux kernel team's efforts to
mitigate the practical consequences of this problem without resorting to
breaking backwards compatibility.</p>
<p>This design is generally agreed to be a bad idea. As far as we can
tell, there are no use cases whatsoever in which this is the behavior
you actually want. It has led to the use of insecure <tt class="docutils literal">ssh</tt> keys on
real systems, and many *nix-like systems (including at least Mac OS
X, OpenBSD, and FreeBSD) have modified their <tt class="docutils literal">/dev/urandom</tt>
implementations so that they never return predictable outputs, either
by making reads block in this case, or by simply refusing to run any
userspace programs until the system RNG has been
initialized. Unfortunately, Linux has so far been unable to follow
suit, because it's been empirically determined that enabling the
blocking behavior causes some currently extant distributions to
fail to boot.</p>
<p>Instead, the new <tt class="docutils literal">getrandom()</tt> syscall was introduced, making
it <em>possible</em> for userspace applications to access the system random number
generator safely, without introducing hard to debug deadlock problems into
the system initialization processes of existing Linux distros.</p>
</div>
<div class="section" id="consequences-of-getrandom-availability-for-python">
<h2><a class="toc-backref" href="#id35">Consequences of <tt class="docutils literal">getrandom()</tt> availability for Python</a></h2>
<p>Prior to the introduction of the <tt class="docutils literal">getrandom()</tt> syscall, it simply wasn't
feasible to access the Linux system random number generator in a provably
safe way, so we were forced to settle for reading from <tt class="docutils literal">/dev/urandom</tt> as the
best available option. However, with <tt class="docutils literal">getrandom()</tt> insisting on raising an
error or blocking rather than returning predictable data, as well as having
other advantages, it is now the recommended method for accessing the kernel
RNG on Linux, with reading <tt class="docutils literal">/dev/urandom</tt> directly relegated to &quot;legacy&quot;
status. This moves Linux into the same category as other operating systems
like Windows, which doesn't provide a <tt class="docutils literal">/dev/urandom</tt> device at all: the
best available option for implementing <tt class="docutils literal">os.urandom()</tt> is no longer simply
reading bytes from the <tt class="docutils literal">/dev/urandom</tt> device.</p>
<p>This means that what used to be somebody else's problem (the Linux kernel
development team's) is now Python's problem -- given a way to detect that the
system RNG is not initialized, we have to choose how to handle this
situation whenever we try to use the system RNG.</p>
<p>It could simply block, as was somewhat inadvertently implemented in 3.5.0:</p>
<pre class="literal-block">
# artist's impression of the CPython 3.5.0-3.5.1 behavior
def generate_unpredictable_bytes_or_block(num_bytes):
    while not system_rng_is_ready:
        wait
    return unpredictable_bytes(num_bytes)
</pre>
<p>Or it could raise an error, as this PEP proposes (in <em>some</em> cases):</p>
<pre class="literal-block">
# artist's impression of the behavior proposed in this PEP
def generate_unpredictable_bytes_or_raise(num_bytes):
    if system_rng_is_ready:
        return unpredictable_bytes(num_bytes)
    else:
        raise BlockingIOError
</pre>
<p>Or it could explicitly emulate the <tt class="docutils literal">/dev/urandom</tt> fallback behavior,
as was implemented in 3.5.2rc1 and is expected to remain for the rest
of the 3.5.x cycle:</p>
<pre class="literal-block">
# artist's impression of the CPython 3.5.2rc1+ behavior
def generate_unpredictable_bytes_or_maybe_not(num_bytes):
    if system_rng_is_ready:
        return unpredictable_bytes(num_bytes)
    else:
        return (b&quot;p4ssw0rd&quot; * (num_bytes // 8 + 1))[:num_bytes]
</pre>
<p>(And the same caveats apply to this sketch as applied to the
<tt class="docutils literal">generate_unpredictable_password</tt> sketch of <tt class="docutils literal">/dev/urandom</tt> above.)</p>
<p>There are five places where CPython and the standard library attempt to use the
operating system's random number generator, and thus five places where this
decision has to be made:</p>
<ul class="simple">
<li>initializing the SipHash used to protect <tt class="docutils literal">str.__hash__</tt> and
friends against DoS attacks (called unconditionally at startup)</li>
<li>initializing the <tt class="docutils literal">random</tt> module (called when <tt class="docutils literal">random</tt> is
imported)</li>
<li>servicing user calls to the <tt class="docutils literal">os.urandom</tt> public API</li>
<li>the higher level <tt class="docutils literal">random.SystemRandom</tt> public API</li>
<li>the new <tt class="docutils literal">secrets</tt> module public API added by <a class="reference external" href="/dev/peps/pep-0506">PEP 506</a></li>
</ul>
<p>Currently, these five places all use the same underlying code, and
thus make this decision in the same way.</p>
<p>This whole problem was first noticed because 3.5.0 switched that
underlying code to the <tt class="docutils literal">generate_unpredictable_bytes_or_block</tt> behavior,
and it turns out that there are some rare cases where Linux boot
scripts attempted to run a Python program as part of system initialization, the
Python startup sequence blocked while trying to initialize SipHash,
and then this triggered a deadlock because the system stopped doing
anything -- including gathering new entropy -- until the Python script
was forcibly terminated by an external timer. This is particularly unfortunate
since the scripts in question never processed untrusted input, so there was no
need for SipHash to be initialized with provably unpredictable random data in
the first place. This motivated the change in 3.5.2rc1 to emulate the old
<tt class="docutils literal">/dev/urandom</tt> behavior in all cases (by calling <tt class="docutils literal">getrandom()</tt> in
non-blocking mode, and then falling back to reading <tt class="docutils literal">/dev/urandom</tt>
if the syscall indicates that the <tt class="docutils literal">/dev/urandom</tt> pool is not yet
fully initialized.)</p>
<p>A similar problem was found due to the <tt class="docutils literal">random</tt> module calling
<tt class="docutils literal">os.urandom</tt> as a side-effect of import in order to seed the default
global <tt class="docutils literal">random.Random()</tt> instance.</p>
<p>We have not received any specific complaints regarding direct calls to
<tt class="docutils literal">os.urandom()</tt> or <tt class="docutils literal">random.SystemRandom()</tt> blocking with 3.5.0 or 3.5.1 -
only problem reports due to the implicit blocking on interpreter startup and
as a side-effect of importing the random module.</p>
<p>Accordingly, this PEP proposes providing consistent shared behaviour for the
latter three cases (ensuring that their behaviour is unequivocally suitable for
all security sensitive operations), while updating the first two cases to
account for that behavioural change.</p>
<p>This approach should mean that the vast majority of Python users never need to
even be aware that this change was made, while those few whom it affects will
receive an exception at runtime that they can look up online and find suitable
guidance on addressing.</p>
</div>
</div>
<div class="section" id="references">
<h1><a class="toc-backref" href="#id36">References</a></h1>
<table class="docutils footnote" frame="void" id="id9" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id1">[1]</a></td><td>os.urandom() should use Linux 3.17 getrandom() syscall
(<a class="reference external" href="http://bugs.python.org/issue22181">http://bugs.python.org/issue22181</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id10" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id2">[2]</a></td><td>Python 3.5 running on Linux kernel 3.17+ can block at startup or on
importing the random module on getrandom()
(<a class="reference external" href="http://bugs.python.org/issue26839">http://bugs.python.org/issue26839</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id11" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id3">[3]</a></td><td>&quot;import random&quot; blocks on entropy collection on Linux with low entropy
(<a class="reference external" href="http://bugs.python.org/issue25420">http://bugs.python.org/issue25420</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id12" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id4">[4]</a></td><td>os.urandom() doesn't block on Linux anymore
(<a class="reference external" href="https://hg.python.org/cpython/rev/9de508dc4837">https://hg.python.org/cpython/rev/9de508dc4837</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id13" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id5">[5]</a></td><td>Proposal to add os.getrandom()
(<a class="reference external" href="http://bugs.python.org/issue26839#msg267803">http://bugs.python.org/issue26839#msg267803</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id14" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id6">[6]</a></td><td>Add os.urandom_block()
(<a class="reference external" href="http://bugs.python.org/issue27250">http://bugs.python.org/issue27250</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id15" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id7">[7]</a></td><td>Add random.cryptorandom() and random.pseudorandom, deprecate os.urandom()
(<a class="reference external" href="http://bugs.python.org/issue27279">http://bugs.python.org/issue27279</a>)</td></tr>
</tbody>
</table>
<table class="docutils footnote" frame="void" id="id16" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id8">[8]</a></td><td>Always use getrandom() in os.random() on Linux and add
block=False parameter to os.urandom()
(<a class="reference external" href="http://bugs.python.org/issue27266">http://bugs.python.org/issue27266</a>)</td></tr>
</tbody>
</table>
<p>For additional background details beyond those captured in this PEP, also see
Victor Stinner's summary at <a class="reference external" href="http://haypo-notes.readthedocs.io/pep_random.html">http://haypo-notes.readthedocs.io/pep_random.html</a></p>
</div>
<div class="section" id="copyright">
<h1><a class="toc-backref" href="#id37">Copyright</a></h1>
<p>This document has been placed into the public domain.</p>
<!-- Local Variables:
mode: indented-text
indent-tabs-mode: nil
sentence-end-double-space: t
fill-column: 70
coding: utf-8 -->
</div>

